### ISSUE TITLE
Planet released yet?

### ISSUE THREAD

**Issue by Penguinplus123** [ThomasThings/xenacia#4]
Unsure whether the planet is released, as I cannot find it.

**Comment by ThomasThings** [comment]
It's not. I'm nowhere near getting to that point in the mod.
I plan to code the planet once I've finished at least 90% of the content. (Units, Blocks, etc...)

**Comment by Penguinplus123** [comment]
Ah, I see. Do you think you'd need help? Looking for something to do related to modding/gamedev.

**Comment by ThomasThings** [comment]
No, it's not really something I need help with. I just need to learn to take breaks every once in a while when I'm making no progress, so when I get back I actually get things done.
