### ISSUE TITLE
bugged sprite

### ISSUE THREAD

**Issue by UnionofSovietSocialistRepublics** [ThomasThings/xenacia#6]
![image](https://github.com/ThomasThings/xenacia/assets/71920146/1d123be1-d13b-4ad2-8bcd-5e1c70750fe1)

![image](https://github.com/ThomasThings/xenacia/assets/71920146/9e9bd0ac-c75d-446c-9bc1-e33f38ac66cd)

**Comment by ThomasThings** [comment]
yeah, everything in Xenacia is getting a total re-work, so they'll be fixed when I get around to them.
