### ISSUE TITLE
Question regarding communication

### ISSUE THREAD

**Issue by TagGamer555** [ThomasThings/xenacia#7]
I wanted to ask if it is possible to engage in a private conversation regarding Xenacia mod. I mostly want to leave feedback before you get too deep into what I think are misunderstandings of various RTS game concepts. If you do not wish to, that's fine, just let me know.

**Comment by ThomasThings** [comment]
Yeah that's totally possible. Discord would likely be the best platform to do that on, and my username is [thomas_has_things].

Just to let you know though, the mod is currently not in development and won't be for a good long while. It also was hardly in a state even remotely close to done, and the chances are I'll start over from scratch again once I get back from my burout hiatus.

**Comment by TagGamer555** [comment]
Hi, sorry, I forgot entirely about this >.<
I currently have no way of accessing Discord, but when I do, my username is on this GitHub account just so you can be sure
My internet connection doesn't want to cooperate at the moment, but I'll contact you as soon as possible

**Comment by TagGamer555** [comment]
Oh, and I'm just going to leave my feedback here for obvious reasons:
* The artstyle in both versions of Xenacia is appeaing to look at, and the color choice is great as well
* In "modern" Xenacia, the naming of some of the structures is weird, like an "Igniter" generator
* I am not a big fan of shift from less to more fictional content in modern Xenacia in general
* Though not the biggest problem, I'd argue that you got the unit classes/archetypes incorrectly; here's my take on them:
* * Offensive units are great against enemy structures, and have an ability to damage multiple structures or be more effective against them
* * Defensive units are great against enemy units, and use weapons to counter enemy abilities, for example, adding a DoT debuff against regeneration, homing against speed, knockback against suicide bombers, etc.
* * Supportive units are great for supporting you and other units, whether it is resource management, repairs, rebuilding, buffing units, etc.


Overall, I think **the visual aspect is great, and the gameplay aspect is on the weaker side**, and is definitely what you could improve either for the next iteration/update of Xenacia.

I hope this helps, sorry for the wait >.<

**Comment by ThomasThings** [comment]
No worries about the wait

And yeah I kinda 100% agree with you on basically all of that. But to be honest there's not alot I can do about most of it at the moment, as time is extremely limited, and skill and motivation are severely lacking. But, I am working on regaining skill and motivation, so here's to hoping I can fix some of these issues.

**Comment by TagGamer555** [comment]
Don't worry, as a player since 2015 I feel ya :D

**Comment by TagGamer555** [comment]
Also can I still hit you up on Discord when I'll have the chance?

**Comment by ThomasThings** [comment]
For sure, it's much more reliable than recieving your messages through my
laggy email.

**Comment by TagGamer555** [comment]
Aight then, I'll see you there. :)
